name: Build MaterialFiles

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Decode Keystore
        run: |
          printf '%s' "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.jks
          ls -lh release.jks

      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/35.0.0/apksigner sign \
          --ks release.jks \
          --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
          --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
          --key-pass pass:${{ secrets.ANDROID_KEY_PASSWORD }} \
          --out app/build/outputs/apk/release/Files-release.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Files-release
          path: app/build/outputs/apk/release/Files-release.apk
          retention-days: 10